SELECT 
    A.AUTHOR_ID,
    B.AUTHOR_NAME,
    A.CATEGORY,
    SUM(A.PRICE * S.SALES) AS SALES
FROM BOOK AS A
JOIN AUTHOR AS B
    ON A.AUTHOR_ID = B.AUTHOR_ID
JOIN BOOK_SALES AS S
    ON A.BOOK_ID = S.BOOK_ID
WHERE S.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY 
    A.AUTHOR_ID,
    B.AUTHOR_NAME,
    A.CATEGORY
ORDER BY
    A.AUTHOR_ID ASC,
    A.CATEGORY DESC;
