# SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
# FROM REST_INFO A
# JOIN (
#     SELECT FOOD_TYPE, MAX(FAVORITES) MAX_FAVORITES
#     FROM REST_INFO
#     GROUP BY FOOD_TYPE
# ) B
# ON A.FOOD_TYPE = B.FOOD_TYPE
# AND A.FAVORITES = B.MAX_FAVORITES
# ORDER BY A.FOOD_TYPE DESC

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (
    SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES,
        RANK() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS rnk
    FROM REST_INFO
) AS A
WHERE rnk = 1
ORDER BY FOOD_TYPE DESC