# SELECT COUNT(ID) AS FISH_COUNT
# FROM FISH_INFO
# WHERE FISH_TYPE = (
#     SELECT FISH_TYPE
#     FROM FISH_NAME_INFO
#     WHERE FISH_NAME IS 'BASS'
#     OR FISH_NAME IS 'SNAPPER'
# )

SELECT COUNT(ID) AS FISH_COUNT
FROM FISH_INFO AS A
JOIN FISH_NAME_INFO AS B
ON A.FISH_TYPE = B.FISH_TYPE
WHERE B.FISH_NAME = 'BASS'
OR B.FISH_NAME = 'SNAPPER'