# SELECT 
#     SUM(C.SCORE) SCORE,
#     B.EMP_NO, 
#     B.EMP_NAME, 
#     B.POSITION,
#     B.EMAIL
# FROM HR_DEPARTMENT A
# JOIN HR_EMPLOYEES B
#     ON A.DEPT_ID = B.DEPT_ID
# JOIN HR_GRADE C
#     ON B.EMP_NO = C.EMP_NO
# WHERE C.YEAR = 2022
# GROUP BY B.EMP_NO
# ORDER BY SCORE DESC
# LIMIT 1 # 가장 높은 점수를 가진 사람이 두 명 이상일 가능성 있음

WITH SUM_SCORE AS (
    SELECT
        SUM(B.SCORE) SCORE,
        A.EMP_NO,
        A.EMP_NAME,
        A.POSITION,
        A.EMAIL
    FROM HR_EMPLOYEES A
    JOIN HR_GRADE B
        ON A.EMP_NO = B.EMP_NO
    WHERE B.YEAR = 2022
    GROUP BY A.EMP_NO
)

SELECT *
FROM SUM_SCORE
WHERE SCORE = (SELECT MAX(SCORE) FROM SUM_SCORE)