# SELECT A.CATEGORY, B.MAX_PRICE, A.PRODUCT_NAME
# FROM FOOD_PRODUCT A
# JOIN (
#     SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
#     FROM FOOD_PRODUCT
#     WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
#     GROUP BY CATEGORY
# ) B
# ON A.CATEGORY = B.CATEGORY
# AND A.PRICE = B.MAX_PRICE
# ORDER BY B.MAX_PRICE DESC

SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM (
    SELECT CATEGORY, PRICE, PRODUCT_NAME,
        RANK() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) AS rnk
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
) A # 서브쿼리를 테이블처럼 쓸 때는 반드시 별칭 붙여야 함
WHERE rnk = 1
ORDER BY PRICE DESC