WITH CTE AS (
    SELECT
        CASE
            WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') > 0
            AND SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE NAME = 'Python') > 0
            THEN "A"
            WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE NAME = 'C#') > 0
            THEN "B"
            WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') > 0
            THEN "C"
        END AS GRADE, ID
    FROM DEVELOPERS
)

SELECT B.GRADE, B.ID, A.EMAIL
FROM DEVELOPERS A
JOIN CTE B
    ON A.ID = B.ID
WHERE B.GRADE IS NOT NULL
ORDER BY B.GRADE, B.ID